# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='celular_cliente',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='correo_cliente',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega_pedido',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
